// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMEBu53UMIA0_TPSM5Wfxxs6Rlplj9tkQ',
    appId: '1:884282985214:web:99179e68b6dc9278aab3af',
    messagingSenderId: '884282985214',
    projectId: 'fooddeliveryapp-b2cd7',
    authDomain: 'fooddeliveryapp-b2cd7.firebaseapp.com',
    databaseURL: 'https://fooddeliveryapp-b2cd7-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliveryapp-b2cd7.firebasestorage.app',
    measurementId: 'G-YZ8BGJ00QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNnQNe4BmgDB1Ni6OVeAovvRws4pbNWC0',
    appId: '1:884282985214:android:a665b25053898e9daab3af',
    messagingSenderId: '884282985214',
    projectId: 'fooddeliveryapp-b2cd7',
    databaseURL: 'https://fooddeliveryapp-b2cd7-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliveryapp-b2cd7.firebasestorage.app',
  );

}